name: Deploy to WordPress.org
on:
  push:
    branches:
      - master
jobs:
  release:
    name: New Release
    runs-on: ubuntu-latest
    steps:
    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: product-of-origin